def build(bld):
    bld.stlib(
        source = [
            'recommender.cpp',
            'anomaly.cpp',
            'weight_manager.cpp',
            'local_storage.cpp',
            'local_storage_mixture.cpp',
            'column_table.cpp',
            'labels.cpp',
            ],
        target = 'jubatus_dump'
        )

    def make_test(src):
        bld.program(
            features = 'gtest',
            target = src[0: src.find('.')],
            source = src,
            use = 'jubatus_dump JUBATUS_CORE',
            )

    make_test('types_test.cpp')
    make_test('classifier_test.cpp')
    make_test('weight_manager_test.cpp')
